ARG DOCKER_BASE_URL="gitlab.inf.unibz.it:4567"
ARG EARTHLY_GIT_PROJECT_NAME  # https://docs.earthly.dev/earthfile/builtin-args
ARG GIT_PROJECT_NAME="commul/docker/tools/texlive"
ARG DOCKER_URL="$DOCKER_BASE_URL/$GIT_PROJECT_NAME/2019/minimal"
ARG COMMUL_REGISTRY_URL="https://gitlab.inf.unibz.it/commul/docker/tools/texlive/container_registry/"
ARG LABEL_VCS_URL="https://gitlab.inf.unibz.it/commul/docker/tools/texlive"
ARG AUTHOR="Egon W. Stemle <egon.stemle@eurac.edu>"
ARG MAINTAINER="Egon W. Stemle <egon.stemle@eurac.edu>"

docker:
    ARG UBUNTU_IMG_VERSION=20.04

    FROM ubuntu:$UBUNTU_IMG_VERSION
    LABEL author="Thorsten Winkler <https://github.com/thorsten-winkler>"
    LABEL maintainer=$MAINTAINER

    ENV TEMPDIR /tmp/install-tl
    WORKDIR $TEMPDIR

    ENV PERSISTENT_DEPS \
        fontconfig \
        git \
        gpg \
        perl \
        vim \
        wget

    ARG TL_PROFILE=texlive-2019-minimal.profile
    COPY $TL_PROFILE .

    ENV PATH $PATH:/usr/local/texlive/2019/bin/x86_64-linux
    ENV MANPATH $MANPATH:/usr/local/texlive/2019/texmf-dist/doc/man
    ENV INFOPATH $INFOPATH:/usr/local/texlive/2019/texmf-dist/doc/info

    RUN apt update -y && apt upgrade -y && mkdir -p /docs && \
        apt install -y $PERSISTENT_DEPS && \
        # TL installation
        wget ftp://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2019/tlnet-final/install-tl-unx.tar.gz && \
        tar xfz install-tl-unx.tar.gz --strip-components=1 && \
        ./install-tl --repository ftp://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2019/tlnet-final --profile=$TL_PROFILE

    WORKDIR /docs

    # Cleanup
    RUN rm -rf $TEMPDIR && \
        apt autoclean -y && \
        apt autoremove -y && \
        apt clean -y && \
        apt purge -y && \
        apt remove --purge -y

    ARG EARTHLY_TARGET_TAG
    ARG EARTHLY_GIT_HASH
    LABEL org.label-schema.schema-version="1.0" \  # http://label-schema.org/rc1/
          org.label-schema.version="$EARTHLY_TARGET_TAG" \
          org.label-schema.vcs-url="$LABEL_VCS_URL" \
          org.commul.git-hash="$EARTHLY_GIT_HASH" \
          org.commul.registry-url="$COMMUL_REGISTRY_URL" \
          org.commul.docker-url="$DOCKER_URL"
    
    SAVE IMAGE --push "$DOCKER_URL:latest"
    SAVE IMAGE --push "$DOCKER_URL:$EARTHLY_TARGET_TAG"
